sonar.projectKey=AltairaLabs_promptpack-python
sonar.organization=altairalabs

sonar.sources=packages/promptpack/src,packages/promptpack-langchain/src
sonar.tests=packages/promptpack/tests,packages/promptpack-langchain/tests
sonar.python.version=3.10, 3.11, 3.12, 3.13
sonar.python.coverage.reportPaths=packages/promptpack/coverage-promptpack.xml,packages/promptpack-langchain/coverage-langchain.xml

sonar.sourceEncoding=UTF-8
